Create categories
fourth-team-core/our_blog pull request #20
Opened 2022-08-19 04:30 UTC by DmitryBBB

Создал тэг для категорий, немного поправил карточку post_list

2022-08-19 13:08 UTC, ZaitcevIlya requested changes

2022-08-19 13:08 UTC, ZaitcevIlya commented on blog/templates/tags/categories_list.html
> +    <li><a href="#">{{ category.name }}</a></li>
Здесь в href подставь "/{{ category.name }}/", или что-то такое.  @DmitryBBB

2022-08-19 13:08 UTC, ZaitcevIlya commented on blog/blog/urls.py
> +    # path("category<slug:id>", CategoryPostsList.as_view(), name="category_posts_lst")
Тут в path можешь передавать "/<category:name>/". Проверь точно как там путь будет. @DmitryBBB

2022-08-23 18:51 UTC, DmitryBBB commented on blog/blog/urls.py
> +    # path("category<slug:id>", CategoryPostsList.as_view(), name="category_posts_lst")
Илья получилось сделать через id category, добавил ссылку в post_list для перехода по категориям, как вытащить category.name пока не вкусил

2022-08-29 18:38 UTC, merged